services:
    db:
        image: mysql:8.0
        container_name: management-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password123
            MYSQL_DATABASE: management
            MYSQL_USER: myuser
            MYSQL_PASSWORD: password123
        ports:
            - "3308:3306"
        volumes:
            - management-db:/var/lib/mysql
        networks:
            - laravel_network
networks:
    laravel_network:

volumes:
    management-db:
